### ISSUE TITLE
Test/Review OsteoBioR updates for plots

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/OsteoBioR#51]
@isomemo Except of one left point all other features are implemented with version [24.04.1](https://github.com/Pandora-IsoMemo/osteo-bior/pull/46) and ready for [testing on the beta](https://isomemoapp.com/app/osteo-bio-r-beta) version. Feel free to test the updates

> - [x] Option to choose plot(s) symbols and colours -> https://github.com/Pandora-IsoMemo/osteo-bior/pull/44 (1)
> - [x] Option to add/edit plot(s) legend (2)
> - [x] When having two y-axes (one on the left and another one on the right of the plot). Have the option to switch their positions. (3)
> - In the **export of plot results** include columns for: (4)
>   - [x] median value of interval and 
>   - [x] corresponding y value (and 
>     - [x] SD and 
>     - [x] user set credible interval).  
>   - [ ] Users can use default options or select a temporal  resolution (x-axis) for sampling of y values. 
>   - [x] A column gives row number (1,2,3…) for each estimate.  

 I will open separate issues for the left.

_Originally posted by @arunge in https://github.com/Pandora-IsoMemo/osteo-bior/issues/43#issuecomment-2077109882_

![image](https://github.com/Pandora-IsoMemo/osteo-bior/assets/16759098/34ad53a0-240e-4a0b-84d6-2b0273df656a)

**Comment by isomemo** [comment]
@arunge 
@CarloCocozza you should comment on this when you are feeling better ;-)

**Comment by CarloCocozza** [comment]
Hi @arunge , I have tested the plot production. Overall this works well. I just have to report a few things:

-there is an error in the mathematical annotation example: "Bayesian Estimated" ~ delta^~13*C ~ ("‰" - ~ "VPDB") should be "Bayesian Estimated" ~ delta^~13~C ~ ("‰" - ~ "VPDB") otherwise the C will be superscript as well.
-I may need mathematical annotation also in the legend names, which as we discussed, should be done by saving the original model name with a new name. 
-I did not understand how to remove the secondary axis if I do not need it anymore
-There should be the same options for the secondary axis as in the y-axis (size, colour, font, etc.). Moreover, here is also needed the mathematical annotation.
-discussion as in #55 about single measurements gaps (i.e. possibility to manually add single dots)

Regarding the Mcp package (#49 ) I do not understand how to tell the package which model to consider (I refer to OsteoBioR model, not Mcp model).

**Comment by arunge** [comment]
With version [24.10.0](https://github.com/Pandora-IsoMemo/OsteoBioR/pull/73) on [OsteoBioR beta](https://isomemoapp.com/app/osteo-bio-r-beta) I pushed following of your notes from [above](https://github.com/Pandora-IsoMemo/OsteoBioR/issues/51#issuecomment-2380722455):

> - [x] there is an error in the mathematical annotation example: "Bayesian Estimated" ~ delta^~13*C ~ ("‰" - ~ "VPDB") should be "Bayesian Estimated" ~ delta^~13~C ~ ("‰" - ~ "VPDB") otherwise the C will be superscript as well.
> - [x] There should be the same options for the secondary axis as in the y-axis (size, colour, font, etc.). Moreover, here is also needed the mathematical annotation.

Regarding the next points:

> - I did not understand how to remove the secondary axis if I do not need it anymore

Please just remove the text from the input 'Add a new secondary axis' and press 'Apply'. This removes the 2nd y axis. Currently, this only works with the [beta version](https://isomemoapp.com/app/osteo-bio-r-beta). I will push the changes to the main when we are done here.

> Regarding the Mcp package (#49 ) I do not understand how to tell the package which model to consider (I refer to OsteoBioR model, not Mcp model).

Please, check [here](https://github.com/Pandora-IsoMemo/OsteoBioR/issues/49#issuecomment-2413310690).

> -discussion as in #55 about single measurements gaps (i.e. possibility to manually add single dots)

Please, check [here](https://github.com/Pandora-IsoMemo/OsteoBioR/issues/55#issuecomment-2413369688).

> - I may need mathematical annotation also in the legend names, which as we discussed, should be done by saving the original model name with a new name.

This will not be possible that easily. I cannot use mathematical annotations as model names, here only text is possible. Than we must develop a new user inputs to update the legend texts when creating the plot. This step must be planned first, and needs some more time.

**Comment by arunge** [comment]
Regarding 

> > - I may need mathematical annotation also in the legend names, which as we discussed, should be done by saving the original model name with a new name.
> 
> This will not be possible that easily. I cannot use mathematical annotations as model names, here only text is possible. Than we must develop a new user inputs to update the legend texts when creating the plot. This step must be planned first, and needs some more time.

Implementation of the option to edit legend texts will be a future task. I will push the current beta version to the main app and close this issue.
