### ISSUE TITLE
Code for point change detection

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/OsteoBioR#61]
@arunge I have attached the R code for point change detection (plus example data) to be implemented in OsteoBioR. The relevant comments for the implementation are marked in red. Please give priority to implement this code.

[test.csv](https://github.com/user-attachments/files/16675121/test.csv)
[code OsteoBioR.docx](https://github.com/user-attachments/files/16675122/code.OsteoBioR.docx)

**Comment by arunge** [comment]
Note from todays meeting: code on github: https://github.com/Pandora-IsoMemo/ChangeR/blob/main/ChangeR%20v%200.01.txt

**Comment by isomemo** [comment]
@arunge in the Word file I have added comments in red to document the original code. Please rely on this instead.

**Comment by arunge** [comment]
@isomemo JFYI: the checks were passed when loading the  `mcp` package, see: https://github.com/Pandora-IsoMemo/OsteoBioR/pull/62. That is, including `mcp` into our docker container succeeded. 

Next, we can start to check and integrate your code.

**Comment by arunge** [comment]
@isomemo With [version 24.08.2](https://github.com/Pandora-IsoMemo/OsteoBioR/pull/62) on [OsteoBioR beta](https://isomemoapp.com/app/osteo-bio-r-beta), I added the option to apply a 'break point detection'. Please test the feature and let me know about any issues. Please check details regarding the new version [here](https://github.com/Pandora-IsoMemo/OsteoBioR/pull/62#issue-2475489026).
The input for the 'Segments' and 'Priors' matrices are more basic than in ReSources. I wanted to keep the input as simple as possible while still ensuring some comfort (Cell ID's are incremented by one when content for a cell was 'Set'; and Cell ID's are labelled by their row/column).

You can check your code which now lives in several functions here:
- https://github.com/Pandora-IsoMemo/OsteoBioR/blob/beta/R/02-breakPoints.R

Currently, I also do print the mcp lists that are the input for the model. However, this is just for now to check if all works as expected. We might remove this output (1) in the future.

We can also discuss next time which measures should be added for model comparison, currently only "loo" (2) is printed. Please, let me know if you have questions!

![image](https://github.com/user-attachments/assets/33a308d6-5f1c-4c3e-882a-0693269f6088)

![image](https://github.com/user-attachments/assets/8dc77f2f-87f6-4223-bafb-27105fbefa30)

**Comment by arunge** [comment]
I need to add two more options of model comparison:
- [ ] WAIC test
- [ ] Heuristic comparison

**Comment by arunge** [comment]
Continuing [here](https://github.com/Pandora-IsoMemo/OsteoBioR/issues/49#issuecomment-2378794917).
